### ISSUE TITLE
Issue while running timeloop-mapper

### ISSUE THREAD

**Issue by suyashbakshi** [NVlabs/timeloop#113]
Hello,
while trying to run a simple experiment with mapper, I'm getting the following error:
```
~/my/timeloop-dev/timeloop$ timeloop-mapper myarch.arch.yaml alexnet_L4.prob.yaml mymapper.mapper.yaml
  _______                __                
 /_  __(_)___ ___  ___  / /___  ____  ____ 
  / / / / __ `__ \/ _ \/ / __ \/ __ \/ __ \
 / / / / / / / / /  __/ / /_/ / /_/ / /_/ /
/_/ /_/_/ /_/ /_/\___/_/\____/\____/ .___/ 
                                  /_/      

MESSAGE: attempting to read problem shape from file: /home/suyash/my/timeloop-dev/timeloop/problem-shapes/cnn-layer.yaml
Problem configuration complete.
ERROR: key not found: arithmetic, at line: 0```

I'm sure its probably a simple fix, but would greatly appreciate some help with it. Attached are the mapper, architecture and problem files I'm using. Attaching in txt format since github isnt allowing upload of yaml format.

Thanks
-Suyash

[alexnet_L4.prob.txt](https://github.com/NVlabs/timeloop/files/7866453/alexnet_L4.prob.txt)
[myarch.arch.txt](https://github.com/NVlabs/timeloop/files/7866454/myarch.arch.txt)
[mymapper.mapper.txt](https://github.com/NVlabs/timeloop/files/7866455/mymapper.mapper.txt)

**Comment by angshuman-parashar** [comment]
Version should be 0.2.

**Comment by suyashbakshi** [comment]
Thank you. But now I get a different error:
```
~/my/timeloop-dev/timeloop/my_experiments$ timeloop-mapper myarch.arch.yaml alexnet_L4.prob.yaml mymapper.mapper.yaml
  _______                __                
 /_  __(_)___ ___  ___  / /___  ____  ____ 
  / / / / __ `__ \/ _ \/ / __ \/ __ \/ __ \
 / / / / / / / / /  __/ / /_/ / /_/ / /_/ /
/_/ /_/_/ /_/ /_/\___/_/\____/\____/ .___/ 
                                  /_/      

MESSAGE: attempting to read problem shape from file: /home/suyash/my/timeloop-dev/timeloop/problem-shapes/cnn-layer.yaml
Problem configuration complete.
timeloop-mapper: include/model/attribute.hpp:62: T model::Attribute<T>::Get() const [with T = long unsigned int]: Assertion `specified_' failed.
Aborted (core dumped)
```

**Comment by angshuman-parashar** [comment]
Could you please prepare a tarball (or a concatenated single yaml) so that I can reproduce the issue?

**Comment by angshuman-parashar** [comment]
Based on a quick glance I can see that all your SRAMs are missing sizes (or width, depth). Also there is a typo "attriebutes".
Have you worked through our tutorial videos and examples?

**Comment by suyashbakshi** [comment]
Sure, attaching a concatenated yaml. And corrected the attribute typo.
[input.txt](https://github.com/NVlabs/timeloop/files/7871425/input.txt)

Yes, I'm following the tutorial video. However, I've had trouble finding the attributes of each component and their meanings.

**Comment by suyashbakshi** [comment]
I think I figured it out.

depth * width = size in bits
word-bit * block-size = width

Is there a way to directly specify size of a memory, without worrying about block size etc. It would be useful to have a 'cheat sheet' of attributes.

Also, I had a follow-up question. I want to export all the mappings in a mapspace of a problem, and their associated costs for a specific hardware architecture in order to analyze them. Is there a way to export all the mappings and their cost metadata to a file?

**Comment by angshuman-parashar** [comment]
Those equivalences are correct. In terms of a minimum specification you could just set either `sizeKB` or `entries`, and the other attributes will default to 1.

Regarding exporting all the mappings: if you set the YAML flag `mapper::log-suboptimal` to `True` you will see a compact 1-line descriptor of each mapping in the log as it is evaluated by each mapper thread. Only legal mappings will be emitted.

If you want to emit the mappings in their full loop-nest form you have to replace (or augment) the `mapper.PrintCompact()` call in `mapper-thread.cpp:541` with a call to `mapping.PrettyPrint()` (see `mapper.cpp:443` for an example of how to call `PrettyPrint()`).

If you are using `live-status` the log will be dumped into `timeloop-mapper.log`, otherwise it will be dumped into `stderr`. You can change `mapper.cpp:338` if you want any other custom behavior.

Hope that helps.

**Comment by suyashbakshi** [comment]
Thank you so much. My need is to export all the mappings, i.e. the entire mapspace (whether optimal or suboptimal, but valid), and not just the ones that were sampled by the mapper for cost evaluation.

I will take a look at the modules you mentioned and try to figure it out.

Just one follow up question. Timeloop as of yet does not support "uneven mappings" right? That is, having DMA/memcpy calls for operands at different memory/loop levels?

**Comment by angshuman-parashar** [comment]
Easiest way to dump the mapspace is to use the `linear-pruned` search heuristic and set `search-size` to 0. That will exhaustively walk through the entire mapspace to completion. Use the logging suggestions from my prior comment and you will have a dump of all legal mappings. You could try experimenting with `num-threads` for runtime optimization. If you are limited by file IO speed then it may be best to run with 1 thread.

I could not reconcile the term "uneven mappings" with your description of DMA/memcpy calls. The latter seems to describe explicit-decoupled data-orchestration, which is exactly what Timeloop was designed to model. Instead of a single decoupled DMA engine, Timeloop supports an unlimited hierarchicy of storage levels with a decoupled data-movement engine to move data between each pair of levels (with the option to bypass levels).

**Comment by suyashbakshi** [comment]
Thanks, linear-pruned search should do the job.

Sorry for not being clear. Let me ask using an example:

```
**Even Mapping:**
L0 Memory:

Read new tile of operand B from L1 memory
Read new tile of operand A from L1 memory
for loop_1{	
	for loop_2{
		for loop_3{		
		}
	}
}

**Uneven Mapping:**
L0 Memory:

for loop_1{

	Read new tile of operand B from L1 memory
	
	for loop_2{

		Read new tile of operand A from L1 memory

		for loop_3{
				
		}
	}
}
```
Suppose we have an architecture with L1 and L0 memory. L1 memory contains a tile each of operand A and B, from which L0 iteratively reads a chunk.

L0 memory has 3 nested loops, 'loop_1', 'loop_2' and 'loop_3'.

Now in an even mapping, "read" operation of both operands A and B will be at the topmost loop level in L0. Hence for both operands, we need to store the tile in L0 for the whole operation space of loop_1 * loop_2 * loop_3.

While in an uneven mapping, the "read" operations for operands can be at different loop levels. Hence, for operand A, the tile in L0 will be only stored for operation space of loop_3. While for operand B, the tile stored in L0 will be for operation space of loop_2 * loop_3. 

Hope that makes it a bit clearer.

**Comment by angshuman-parashar** [comment]
I am going to slightly modify the schedules so as to make them consistent with our canonical representation. Essentially what I'm doing is using your loops 1, 2 and 3 to describe the L1::Read --> L0::Fill transfer sequence in two different ways ("uneven" vs. "even"). What happens inside L0 (i.e., L0::Read) is identical in both cases.

**Even Mapping:**
```
== L1 Memory ==
for loop_1 {
    for loop_2 {
        for loop_3 {
            Read new tile of operand B from L1 memory and fill into L0
            Read new tile of operand A from L1 memory and fill into L0        
            == L0 Memory ==
            for loop_4 {
                Read from A/B tiles stored in L0 and do amazing stuff 
            }
        }
    }
}
```

**Uneven Mapping:**

```
== L1 Memory ==
for loop_1 {
   Read new tile of operand B from L1 memory and fill into L0
   for loop_2 {
        Read new tile of operand A from L1 memory and fill into L0        ​
        for loop_3 {
            == L0 Memory ==
            for loop_4 {
               ​Read from A/B tiles stored in L0 and do amazing stuff
            }
       ​}
   ​}
}
```

In this case, yes, Timeloop models the "even" mapping. However, if during traversal of loop_3 Timeloop observes that the tile for A is stationary/does not change (e.g., tile A holds a block of input activations and loop_3 is over output channels), then Timeloop will *not* re-fetch the tile. This applies recursively to all outer loop levels. If Timeloop observes that the tiles are partially overlapping as it walks through loop_3, then it will only fetch the new data (delta) needed to construct the new tile.

Conversely, the "uneven" mapping, as described by the user, is only correct if the operand A tile is stationary across loop_3 and the operand B tile is stationary across loops 2 and 3. But if this is the case, the "even" mapping will automatically result in the "uneven" behavior because Timeloop will discover the stationarity.

My apologies if I have butchered your example and you were trying to explain something else.

**Comment by suyashbakshi** [comment]
Thank you! No you didn't butcher it, in fact your representation is more in line to what I wanted to ask!

I got it, so mainly "even" mappings are modelled (ignoring the stationarity part).

The reason I asked is, with even mapping, say for operand A, one needs to move a tile of A from L1 to L0 that is required only for 1 iteration of loop_3 (assuming no stationarity for A), because of the level at which "Read new tile" operation is assigned.

On the other hand, for uneven mapping, for operand A, one needs to move a tile of A from L1 to L0 that is required by all the iterations of loop_3, because "Read new tile" operation is not encountered until all loop_3 iterations have been executed. Thus, the tile size moved from L1 to L0 will be larger compared to even mapping.

I've used it in my previous work and is good to make a tradeoff between storage requirement and traffic between memory. Would be a cool feature to have in timeloop too.

That's all the questions I had for now, thanks for your patience!

**Comment by angshuman-parashar** [comment]
Yes, you are right, the tile sizes are different in the even and uneven examples above. If you feel this is a useful feature and can show some demonstrable advantages, then please feel free to contribute to the codebase so that all Timeloop users can benefit from it.
