### ISSUE TITLE
About the network cost model

### ISSUE THREAD

**Issue by suyashbakshi** [NVlabs/timeloop#136]
In the example 4 (Spatial Instances) of the hands-on exercise video, what are the assumptions about the network bandwidth between global buffer and the register files?
- To be more precise, in that example, 'K' is partitioned across the PEs, thus causing distinct tiles of weight and output to be sent to each PE. Is this operation of sending distinct tiles to each PE modelled as a bunch of sequential unicast operations? 
Or are the distinct tiles sent simultaneously to each PE? In which case, I would presume the bus leaving the global buffer would need to be very wide to avoid any stalls; ideally as wide as: ```'n' bits * number of PEs``` wide, where 'n' is width of bus entering each PE.

In the same tutorial, for the hardware with "X/Y" dimensions, what is the assumption about the PE interconnectivity? Is there systolic behavior assumed between the PEs? If the systolic behavior is assumed, then is point-to-point connectivity considered between PEs (which does not seem to be the case from diagram shown in tutorial)?

**Comment by angshuman-parashar** [comment]
Timeloop's model has two distinct stages: a microarchitecture-independent tile-analysis stage and a microarchitecture-modeling stage. In terms of the network, the tile analysis stage simply computes the volume of data that must be moved from level i to level i-1 in order to honor the mapping, along with the logical multicast factors and some other statistical data. This data-movement information (across all levels of the architecture) is packaged into a data structure and passed on to the 2nd microarchitectural stage.

The network model is one of the pluggable modules in this 2nd microarchitectural modeling stage. If you look at the source code, you will see that there are several alternative network implementations. You can explicitly instantiate any of these networks from the YAML and hook up buffers/arithmetic units on each side of the network. You can also easily code up and add a new network module and add it to the library of networks available for arch YAMLs to instantiate. If you do not explicitly instantiate a network between any two levels (which is the case for most examples), then a default mesh is instantiated for you.

Each network module must export an Evaluate() method that takes as input a subset of the data-movement information produced by the tile analysis phase and computes the performance and energy cost. Essentially the network module is being told "it's your job to move this volume of data in this specific pattern from the parents to the children, figure out how much perf you can provide and how much energy you are going to burn".

That's the general concept. Within the existing network module implementations, the energy calculations are present but the perf calculation is incomplete. This is because we have been able to model data-movement throttling by setting the read and write bandwidths at the source/destination buffers (which the buffer modules use to determine performance), and have not felt an urgency to model an additional perf chokepoint.

**Comment by suyashbakshi** [comment]
Thank you for the answer. These networks are the ones defined in the "src->model->network-xx.cpp" correct?

So, in 4th para, when you say "model data-movement throttling", am I correct in assuming that for a fan-out network (like in the tutorial example) from global buffer to the PEs, it is possible to define a network having "B bits/cycle" read/write bandwidth at the GB end, and "B/n bits/cycle" bandwidth at each of the "n" PE. Which would essentially enable the multicast operation to be a truly parallel operation? And if this is true, then the memory must be assumed to be multi-ported or having a wide-port?
Or did I misunderstood something?

Also, I'm not sure if it was implicit from your explanation, but to enable a systolic behavior between PEs, would one need to explicitly define a network? Or is that modelled by the default mesh?

**Comment by angshuman-parashar** [comment]
Correct the networks are in src/model/network-xx.hpp/cpp. Base class is in network.hpp/cpp and the factory that instantiates them based on user YAML is in network-factory.hpp/cpp.

Yes, you are correct in principle. But to be clear the existing network modules do not throttle themselves based on bandwidth and so they behave as true multicast networks. Note that this also applies to the output side, which would model in-network reduction instead of multicast. For the memory levels you can specify a read/write bandwidth (words/cycle). As far as perf modeling is concerned Timeloop doesn't really care if this bandwidth is achieved via multiple ports or a wide port. For energy modeling you need to make sure to set the attributes of the buffer correctly (number of ports, width-vs-depth) so that Accelergy can deduce the appropriate energy cost for each access.

We typically do not use the word "systolic" because it is often misused. Data movement in Timeloop is dictated by the mapping. If the mapping indicates that two (or more) sibling nodes receive the same tile at a particular time step t then that tile will be multicast. The network implementations today treat that as a true multicast, meaning that it's the job of the network itself (routers) to produce the duplicate copies and send the data to multiple destinations. However, if the mapping is such that a node has a tile X at time t but its neighbor needs that tile X at time t+1 then that tile will be sent as a "link-transfer" over the same network.

In the former case (i.e., multiple nodes receiving the same data at time t), it's possible to write a new network module that implements the multicast as a store-and-forward operation, but this means each stop on the network must have enough storage to store an entire tile's worth of data, and the cost of moving data will have to account for the additional cost to read and write into this storage structure (which could be the main tiling buffer itself at that node).

**Comment by suyashbakshi** [comment]
Thank you. That clears up quite a few things. Just a few more follow-ups:

- If the network does not throttle based on bandwidth, then say if the sender memory module has higher bandwidth than the bandwidth at which receiver can accept data, then is it presumed that there are "buffering" capabilities at the receiving end? In other words, how is the bandwidth mismatch between two ends handled in terms of perf and energy? Or is this just too fine-grained behavior and Timeloop is not much concerned about it?

- I believe it is implicit and obvious from what your described, but just to confirm, that in case of a fan-out (say from global buffer to PE register files), if the operation is to send distinct data elements to each PE from the GB, but there isn't enough bandwidth on the GB end to serve all operations at once, then the operation will be implicitly accounted for in perf as a bunch of sequential read operations, correct?

- By "link-transfer", you mean just PE-to-PE communication (likely between their RFs) using the same fan-out network that connects them to global buffer, correct? I believe then there will also be a cost difference (both perf and energy) between reading a tile from a neighbor PE and reading from the global buffer. And that cost would likely be modelled by the network.

**Comment by angshuman-parashar** [comment]
* Overall performance is dictated by the throughput of the slowest component. So in your example the receiver will be the bottleneck. You can see if this is happening by looking at the per-level "bandwidth-throttling" stats. If it is less than 1 then it means that level is the culprit.
* If the GB can send 100 bytes per cycle but the PEs can eat them at 200 bytes per cycle then the PEs will effectively eat them at the slower 100 bytes per cycle. That's basically the level of abstraction, and it's intended to cover both scenarios -- a distribution pattern in which the GB serially sends all data to one PE before moving on to the next (i.e., inner-temporal outer-spatial) as well as the other extreme in which the GB sends an element of data to each PE before wrapping back around (i.e., inner-spatial outer-temporal).
* Correct, it's the same network. Cost is modeled in terms of hops and the cost of reading the source and filling the destination. The costs of the primitive network actions (move a distance across wires, go through a router) are the same, but because the source is different (e.g., a large GB vs. a smaller RF) and the destinations are located at different distances from the source, the resultant data movement costs will be different.

BTW, you may know this already but Timeloop has no built-in notion of GB, PE, RF or any such specific architectural construct. The architectural topology is an unlimited tree with nodes at each level representing an opportunity to store a tile from one or more tensors. We as users can and often do use Timeloop to represent this canonical GB+PEs template but there's no real reason to always stick to this overly simplistic template.

**Comment by suyashbakshi** [comment]
Thank you, that clears up a lot of things.

So if understand correctly, the level of abstraction at which timeloop works is: that the network is simply a medium to connect two/more entities like memory modules, arithmetic units. The network does not represent a "bus" in a SoC which would have a certain bandwidth (say a 128-bit wide bus). The bandwidth is dictated by the memory modules' capability to digest incoming data or to send out data to other entity. And the network simply takes the data provided by memory modules or arithmetic units routes it to the correct destination at a rate defined by bandwidths at either ends.

**Comment by angshuman-parashar** [comment]
What you stated is correct for the present _implementation_ of the network plugin modules -- and only for performance. Energy modeling has more fidelity. Moreover, even for performance modeling, the infrastructure (placeholder methods, and data structures passed in to those methods) is there for higher-fidelity analysis should the need arise.

**Comment by vmiheer** [comment]
> However, if the mapping is such that a node has a tile X at time t but its neighbor needs that tile X at time t+1 then that tile will be sent as a "link-transfer" over the same network.

Thank you for this explanation, I was precisely trying to look for trying to understand this thing. Couple of questions:
1. Why such restriction of only allowing neighbor transfers and not generic p2p communication?
2. Is there example which demonstrates this feature? (I'll post it once I create it) More generally is there timeloop test suite?

**Comment by angshuman-parashar** [comment]
> 1. Why such restriction of only allowing neighbor transfers and not generic p2p communication?
It is indeed an arbitrary restriction that we had originally hard-coded because the mesh topology was sufficient for all our use cases. We have considered generalizing this several times but did not have the manpower. Ideally we want to enable all p2p communications, but depending on source and destination the costs could be different (including infinite if the destination cannot be reached from the source). The cost table would have to be part of the arch spec in some form (could be a lambda), and the nest analysis would have to be smart about querying reachability for pairs of nodes, otherwise the analysis complexity would be horrible.
> 2. ... More generally is there timeloop test suite?
Also a high-priority item on our TODO list. We do have a set of tutorial examples, and a single test script in the main repo which could and should all be rolled into a regression suite.

**Comment by vmiheer** [comment]
> We have considered generalizing this several times but did not have the manpower./Also a high-priority item on our TODO list.

Would love to contribute but still waiting for uni approving SLA. (I was out for summer internship but I have nudged them again yesterday).

> including infinite if the destination cannot be reached from the source

I think that would be case only when the network links are directional (nature of directed graph). Other factors affecting reachability would be deadlock causing routing algorithms (but that's orthogonal to topology) or a topology where two sets of nodes can only communicate via shared memory. Not sure which case you are referring to or maybe I am missing something basic 😅.

![multimesh](https://user-images.githubusercontent.com/535650/186983389-75a34f47-6635-4d7b-86cd-20d553a6e800.svg)
(Each square has mesh and they are only connected via shared memory)

**Comment by angshuman-parashar** [comment]
No you're not missing anything. My comment on reachability was in the spirit of being completely general, but a specific example I was thinking of was the disjoint local networks (as you show in your diagram).

**Comment by vmiheer** [comment]
> 2. Is there example which demonstrates this feature? (I'll post it once I create it) 

[e9b23e920edbbda9c76055f12d2e2b90a9c9bf86.patch.txt](https://github.com/NVlabs/timeloop/files/9436958/e9b23e920edbbda9c76055f12d2e2b90a9c9bf86.patch.txt)

**Comment by suyashbakshi** [comment]
I have a quick follow-up. I cannot seem to find any example yaml that explicitly instantiates any of the "custom" networks defined in network-factory. Could you please point me to any example (if there is) or instructions on how to instantiate a network other than the default one in yaml.

Thanks

**Comment by angshuman-parashar** [comment]
https://github.com/Accelergy-Project/timeloop-accelergy-exercises/blob/master/workspace/baseline_designs/example_designs/simple_pim/arch/system_PIM.yaml
