### ISSUE TITLE
Config file for real-world CNNs

### ISSUE THREAD

**Issue by aleczhanshi** [NVlabs/timeloop#18]
Hi there,

I'm trying to evaluate the mapping for real-world CNN benchmarks. Do you have any plan to provide layer specifications in terms of problem configs of those real-world CNNs, such as AlexNet, VGG and ResNet (17 or 50)? If they already exist somewhere, can you point me there?

Zhan

**Comment by angshuman-parashar** [comment]
Take a look at scripts/cnn_layers.py. There are a bunch of layer shapes there. The sample.py script can read in those layers and invoke Timeloop on each of them. Feel free to experiment with these - you can add layers from your favorite networks, or you can download a large number of benchmarks from the DeepBench suite - you'll have to convert the C++ structures into the Python form used here, but it should be a fairly easy script to write because the structures are isomorphic.
