### ISSUE TITLE
couldn't map level DummyBuffer

### ISSUE THREAD

**Issue by aleczhanshi** [NVlabs/timeloop#26]
Hi there,

I got this error `ERROR: couldn't map level DummyBuffer: mapped instances 28 exceeds available hardware instances 16` with the following config file. Could you help explain what the dummy buffer does and where this constraint violation comes from?

```
arch : 
{
  arithmetic : 
  {
    name = "MACs";
    instances = 256;
    word-bits = 16;
    meshX = 16;
  };
  storage = ( 
    {
      name = "PsumRegFile";
      entries = 16;
      instances = 256;
      meshX = 16;
      word-bits = 16;
      read_bandwidth = 2;
      write_bandwidth = 2;
    }, 
    {
      name = "WeightRegFile";
      entries = 192;
      instances = 256;
      meshX = 16;
      word-bits = 16;
      read_bandwidth = 2;
      write_bandwidth = 2;
    }, 
    {
      name = "InputRegFile";
      entries = 12;
      instances = 256;
      meshX = 16;
      word-bits = 16;
      read_bandwidth = 2;
      write_bandwidth = 2;
    }, 
    {
      name = "DummyBuffer";
      entries = 0;
      instances = 16;
      meshX = 16;
      word-bits = 16;
    }, 
    {
      name = "GlobalBuffer";
      sizeKB = 128;
      instances = 1;
      meshX = 1;
      word-bits = 16;
      block-size = 4;
      read_bandwidth = 16;
      write_bandwidth = 16;
    }, 
    {
      name = "DRAM";
      technology = "DRAM";
      instances = 1;
      word-bits = 16;
    } );
};

problem : 
{
  R = 7;
  S = 7;
  P = 112;
  Q = 112;
  C = 3;
  K = 64;
  N = 1;
  Wstride = 2;
  Hstride = 2;
};

mapping = (
    {
      # PsumRegFile
      target = 0;
      type = "datatype";
      keep = [ "Outputs" ];
      bypass = [ "Weights", "Inputs" ];
    },
    {
      # WeightRegFile
      target = 1;
      type = "datatype";
      keep = [ "Weights" ];
      bypass = [ "Inputs", "Outputs" ];
    }, 
    {
      # InputRegFile
      target = 2;
      type = "datatype";
      keep = [ "Inputs" ];
      bypass = [ "Weights", "Outputs" ];
    }, 
    {
      # DummyBuffer
      target = 3;
      type = "datatype";
      keep = [ ];
      bypass = [ "Weights", "Inputs", "Outputs" ];
    }, 
    {
      # GlobalBuffer
      target = 4;
      type = "datatype";
      keep = [ "Inputs", "Outputs" ];
      bypass = [ "Weights" ];
    }, 
    {
      # DRAM
      target = 5;
      type = "datatype";
      keep = [ "Weights", "Inputs", "Outputs" ];
      bypass = [ ];
    }, 
    {
      # PsumRegFile
      target = 0;
      type = "temporal";
      factors = "R1 S1 P1 Q1 C1 K16 N1";
      permutation = "KRSPQCN";
    }, 
    {
      # WeightRegFile
      target = 1;
      type = "temporal";
      factors = "R7 S1 P1 Q1 C1 K1 N1";
      permutation = "CRSPQKN";
    }, 
    {
      # InputRegFile
      target = 2;
      type = "temporal";
      factors = "R1 S1 P1 Q1 C1 K1 N1";
      permutation = "RSPQCKN";
    }, 
    {
      # DummyBuffer
      target = 3;
      type = "spatial";
      factors = "R1 S7 P1 Q1 C1 K1 N1";
      permutation = "CSKRPQN";
      split = 0;
    }, 
    {
      # DummyBuffer
      target = 3;
      type = "temporal";
      factors = "R1 S1 P1 Q1 C1 K1 N1";
      permutation = "RSPQCKN";
    }, 
    {
      # GlobalBuffer
      target = 4;
      type = "spatial";
      factors = "R1 S1 P1 Q28 C1 K1 N1";
      permutation = "QKRSPCN";
      split = 2;
    }, 
    {
      # GlobalBuffer
      target = 4;
      type = "temporal";
      factors = "R1 S1 P16 Q1 C1 K2 N1";
      permutation = "KPRSQCN";
    }, 
    {
      # DRAM
      target = 5;
      type = "temporal";
      factors = "R1 S1 P7 Q4 C3 K2 N1";
      permutation = "QKCPRSN";
    }
);
```

**Comment by angshuman-parashar** [comment]
The specific reason for this error is that the spatial factor `Q28` at the `GlobalBuffer` causes a fanout into 28 instances of the `DummyBuffer` while the architecture only has 16.

The reason for the existence of the DummyBuffer in this configuration is more involved. 
Timeloop’s hardware model organizes units at each level in the hardware hierarchy in a 2-dimensional XY grid. This XY arrangement is exposed architecturally, which means a programmer (or an automated mapper) must explicitly map loops along both dimensions. As you know, whenever you have an amplification in the number of instances between levels, it produces a spatial tiling level you must assign loops to. This spatial tiling level nominally contains 1 loop from each problem dimension. What the “split” directive decides is which loops get mapped onto the X spatial dimension and which get mapped to Y. Split works in conjunction with spatial permutation. For example, setting spatial permutation=“CKRSPQN” and split=0 leads to all loops being mapped to the Y dimension. Split=1 with the same permutation leads to the C loop being mapped to X and KRSPQN being mapped to Y. And so on until split=7, which causes all loops to be mapped to X. Note that depending on the actual available hardware X and Y dimensions, some splits may lead to invalid mappings because you may not have enough hardware units along that dimension. If you are using the timeloop-mapper and you leave split un-set, the mapper will automatically search through all split options for an optimal split point.

But what if you wanted, for example, a C loop along the X dimension and another C loop along the Y dimension at the same spatial level? The split formulation does not allow that, because each loop is only allowed once per spatial level. In hindsight, we realize this was an oversight, and perhaps the X and Y dimensions should have been exposed as different spatial levels. Fortunately, the dummy-buffer workaround can emulate exactly this behavior – by inserting a non-existent dummy buffer, we’ve artificially exposed 2 spatial levels that can be mapped independently. When configuring the hardware, we need to make sure to expand only X at one level and only Y at the other. During mapping, we can now map a full block of loops at each level, with split=7 at one level (to map everything to X) and split=0 at the other (to map everything to Y).

**Comment by aleczhanshi** [comment]
@angshuman-parashar Thanks for the detailed explanation. So, if I understand correctly, does it mean that the multiplication of all spatial factors along the global buffer cannot be greater than 16? 

Moreover, to better understand what you said, which level is the bugged DummyBuffer belong to? Seems that it is attached to the global buffer, but I couldn't find much clue to confirm this. But if that's the case, does this mean that the global buffer is 2D, and if we want any level of hierarchy to be 2-dimensional, we need to have a separate DummyBuffer for that specific level?

**Comment by angshuman-parashar** [comment]
Correct, multiplication of all spatial factors along the global buffer cannot be greater than 16.

The architecture description you pasted is using the older "stacked" format, which enumerates buffer levels from innermost (PSumRegFile) to outermost (DRAM). If you wish you can also use the Accelergy-like nested format (example in https://github.com/Accelergy-Project/timeloop-accelergy-exercises/tree/master/exercises/timeloop/06-mapper-convlayer-eyeriss/arch), which is perhaps more natural to understand. I apologize that we haven't had the opportunity to update all existing configs to the new format.

In this example, GlobalBuffer only has 1 instance so it's not 2D. DummyBuffer has 16 instances, all along MeshX so it's 1D as well.

No, you don't need to use a DummyBuffer simply to create 2D levels -- just set meshX and meshY appropriately to describe the 2D architectural layout of your real buffer levels. The only reason you need a DummyBuffer is if you insist on the ability to map the same problem dimension along both X and Y axes at a particular level. This was the case with Eyeriss -- to faithfully represent the architecture (and its native mapper), we wanted to be able to map the `K` dimension along both X and Y axes of the PE grid, necessitating a DummyBuffer level between the GlobalBuffer and the outermost buffer inside the PE.
