### ISSUE TITLE
Possible to eyeball the type of dataflow from the config file?

### ISSUE THREAD

**Issue by aleczhanshi** [NVlabs/timeloop#28]
Hi there,

It's really nice that in Timeloop we can implement different types of dataflow, such as weight / output / row stationary. I was wondering if there's a clear sign that can tell me which dataflow a config file is corresponding to? For example, the one below from the tutorial 4 is cp-ws. It's pretty clear that it partitioned spatially along the `C` dimension, but which key factors determine that it keeps the weight around in the register file? Put it another way, how should I go about changing it to output / row stationary? Thanks!

```mapping:
  - target: MainMemory
    type: temporal
    factors: R=1 P=1 K=1 C=1
    permutation: PRKC
    
  - target: GlobalBuffer
    type: temporal
    factors: R=3 P=1 K=32 C=2
    permutation: PRKC

  - target: GlobalBuffer
    type: spatial
    factors: R=1 P=1 K=1 C=16
    permutation: PRKC
    
  - target: RegisterFile
    type: temporal
    factors: R=1 P=16 K=1 C=1
    permutation: RPKC
```

**Comment by angshuman-parashar** [comment]
In general stationarity is hierarchical. You can have a different stationarity at each level of the hierarchy. But in these simple examples, I think you're interested in the stationarity behavior at the RF.

To understand that, you need to look at the loop nest at the RF *and* the keep/bypass directives. The loop nest at the RF has P=16 and everything else =1. That means there's only 1 active loop at the RF level that goes through P=[0:16) (if you had more than one active loop you want to look at the innermost loop). What tensors/dataspaces are indexed by P? Outputs and Inputs, but not Weights. That means the tile of Weights inside the loop -- which is just 1 scalar Weight here since it's the absolute innermost loop -- does not change as you go through the P=[0:16). So we have a fairly strong hint that this is a Weight-stationary loop, but we aren't completely there.

Next, we look at the keep/bypass directives. At the RF you'll see that the Weights are kept but Inputs and Outputs are bypassed. Aha, so this means as you go through the P=[0:16) loop, the Weight stored in this register will be held stationary. Ergo, it is a "Weight-Stationary" dataflow.

**Comment by aleczhanshi** [comment]
@angshuman-parashar Thanks for the explanation! I didn't find a bypass option, could you point me to that? Moreover, correct me if I'm wrong, even without the bypass inputs and outputs, the dataflow is still weight-stationary as the weight scalar does not change with `P`, right?

**Comment by aleczhanshi** [comment]
@angshuman-parashar Please bear with me but I have a few higher level questions. 

First, is dataflow a part of hardware model or software mapper? I ask this because it seems like dataflow is fixed by hardware, but at the same time all factors needs to be consistent with the problem, which cannot be determined upfront. For this example, is this correct to say that, when we fix the hardware dataflow to be weight-stationary, we'll determine the factors for each problem in the software, but all factors of RF (`R, C, K` in this example) associated with the weight needs to be 1, and there needs to be at least an active loop in RF, or a non-1 for the rest of factors (`P` here). If it were to be output stationary, all factors in RF (`K, P` in this example) associated with the output needs to be 1, and there has to be at least a non-1 (the active loop) for the rest of factors (`C` or `R` or both).

**Comment by aleczhanshi** [comment]
@angshuman-parashar Second, when we're talking that SCNN is input-stationary and that TPU is weight-stationary and that Eyeriss is row-stationary, are we only talking about the innermost layer of storage, i.e., the register file inside PEs? Is it correct to say that each layer in the storage (RF, global buffer etc.) has some sort of stationarity, but the innermost layer is the most important one?

**Comment by angshuman-parashar** [comment]
> @angshuman-parashar Thanks for the explanation! I didn't find a bypass option, could you point me to that?
Look at exercise 3 in the timeloop/accelergy tutorial: https://github.com/Accelergy-Project/timeloop-accelergy-exercises/tree/master/exercises/timeloop/03-model-conv1d%2Boc-3level. Note that if you're providing a specific mapping to `timeloop-model` then it assumes by default that nothing is bypassed (i.e., all data-spaces are kept at each level).
> Moreover, correct me if I'm wrong, even without the bypass inputs and outputs, the dataflow is still weight-stationary as the weight scalar does not change with `P`, right?
Yeah that's right, but what if you bypass Weights? It's quite likely a really bad mapping, but it's technically legal and it's nothing-stationary (at the RF level).

**Comment by angshuman-parashar** [comment]
> First, is dataflow a part of hardware model or software mapper? I ask this because it seems like dataflow is fixed by hardware, but at the same time all factors needs to be consistent with the problem, which cannot be determined upfront. For this example, is this correct to say that, when we fix the hardware dataflow to be weight-stationary, we'll determine the factors for each problem in the software, but all factors of RF (`R, C, K` in this example) associated with the weight needs to be 1, and there needs to be at least an active loop in RF, or a non-1 for the rest of factors (`P` here). If it were to be output stationary, all factors in RF (`K, P` in this example) associated with the output needs to be 1, and there has to be at least a non-1 (the active loop) for the rest of factors (`C` or `R` or both).
> 
> Moreover, going back to the example from tutorial 4, I believe that the `P` factor in RF could be 2, 4, 8, or 16, and it is all called weight stationary. The determination of `P` should be the job of the mapper right?

I think we kind of visited this issue here: https://github.com/NVlabs/timeloop/issues/21#issuecomment-602838291.
To add to that answer - I believe Joel and Vivienne define dataflows as the permutations of the loop nests - not the factors that form loop bounds. The exception is factors that are forced to 1, meaning that the hardware is incapable of iterating through those dimensions. So in addition to creating the outer levels of software loop nests, a software mapping will also have to fill in the loop bounds (factors) at each of the loops that are otherwise baked into the hardware.

By design, Timeloop is somewhat oblivious to all of this. It doesn't understand "dataflows", all it understands are mappings, mapspaces and mapspace constraints. It's the user's job to set up the constraints to precisely identify the inflexibilities that are baked into the hardware, it's the mapper's job to fill in all available holes, and it's the model's job to take a fully-specified mapping (with no holes) and evaluate its characteristics on the hardware.

**Comment by angshuman-parashar** [comment]
> @angshuman-parashar Second, when we're talking that SCNN is input-stationary and that TPU is weight-stationary and that Eyeriss is row-stationary, are we only talking about the innermost layer of storage, i.e., the register file inside PEs? Is it correct to say that each layer in the storage (RF, global buffer etc.) has some sort of stationarity, but the innermost layer is the most important one?

Yes, each layer has some sort of stationarity. But I can't categorically declare that the innermost layer is the most important one. It really depends on the relative sizing of the buffers, the cost to access them vs. accessing DRAM etc. Stationarity implies reuse of some tensor at the expense of other tensors. The reason you have a multi-level hierarchy is to get some degree of reuse at each level, otherwise you would have bypassed that level. And so stationarity plays a role at each level.

**Comment by aleczhanshi** [comment]
> By design, Timeloop is somewhat oblivious to all of this. It doesn't understand "dataflows", all it understands are mappings, mapspaces and mapspace constraints. It's the user's job to set up the constraints to precisely identify the inflexibilities that are baked into the hardware, it's the mapper's job to fill in all available holes, and it's the model's job to take a fully-specified mapping (with no holes) and evaluate its characteristics on the hardware.

@angshuman-parashar Thanks! Is it correct to say that, it's possible to also bake the factors into the hardware if the accelerator (likely to be on FPGA) is designed for one specific neural network? Otherwise, the factors are usually left unspecified and it's the mapper's job to determine them for each neural networks.

**Comment by aleczhanshi** [comment]
> > @angshuman-parashar Second, when we're talking that SCNN is input-stationary and that TPU is weight-stationary and that Eyeriss is row-stationary, are we only talking about the innermost layer of storage, i.e., the register file inside PEs? Is it correct to say that each layer in the storage (RF, global buffer etc.) has some sort of stationarity, but the innermost layer is the most important one?
> 
> Yes, each layer has some sort of stationarity. But I can't categorically declare that the innermost layer is the most important one. It really depends on the relative sizing of the buffers, the cost to access them vs. accessing DRAM etc. Stationarity implies reuse of some tensor at the expense of other tensors. The reason you have a multi-level hierarchy is to get some degree of reuse at each level, otherwise you would have bypassed that level. And so stationarity plays a role at each level.

@angshuman-parashar Thanks for the clarification. As we discussed, stationarity is a property of each storage layer, but each accelerator only comes with one claimed dataflow, which is the stationarity of the innermost layer. Is there any rational behind this?

**Comment by angshuman-parashar** [comment]
With any architecture, a precise dataflow specification requires you to describe the behavior of every level in the hierarchy. For example, in the SCNN paper we laid out the complete dataflow as a loop nest, and summarized it using the PT-IS-CP moniker. Sadly a loop nest does not make for a great elevator pitch, so perhaps authors use their discretion to highlight a sub-component of the complete dataflow that they may believe is a highlight of the architecture or distinguishes it from prior work. It's not an exact science.

**Comment by aleczhanshi** [comment]
@angshuman-parashar Thanks! It makes a lot of sense.
