### ISSUE TITLE
Handling unspecified block-size and cluster-size

### ISSUE THREAD

**Issue by angshuman-parashar** [NVlabs/timeloop#39]
If a user specifies the word_size and the row_width for a buffer, Timeloop automatically assigns the (row_width / word_size) vector to cluster_size, with block_size being 1. Instead, the vector width should be assigned to block_size (which is more intuitive), with the default cluster_size being 1. A warning will be emitted when Timeloop is making this choice.

**Comment by interrabbit** [comment]
Thank you very much for supplying such a powerful infrastructure.
So can I ask what are the differences between block-size and cluster-size?
As I watched the your config .yaml files,there are some comments"
#   III. Fidelity issue:
#       We use 'block-size' to emulate the parallel reads/writes from the 
#       input and output buffers. However, this creates the problem when K1 
#       and/or C1 are smaller than 16. Timeloop becomes too optimistic because
#       it does not have the notion of a block read boundary. The real 
#       solution is to create parallel input and output buffer instances and use
#       'cluster-size' instead of 'block-size'. TBD.
".
It really confuses me.
By the way, are there any errors about the comments of bandwidth in file "chen-asplos2014.yaml" that describe as "words per cycle"?

**Comment by angshuman-parashar** [comment]
This was fixed in a past update.
