### ISSUE TITLE
Different solutions depending on the number of threads

### ISSUE THREAD

**Issue by egiacomin** [NVlabs/timeloop#46]
Hello,

I am currently using Timeloop (latest commit) on a 2-cores machine. I was experimenting a bit the option "  num-threads: 16" in the mapper.yaml file and found some behavior I am doubtful about:

1- When using 2,8 or 24 threads, the mapper does not find any solution to my particular problem.
2- When using 16 (or even 18) threads, a solution is found. That does not make a lot of sense as I only have 2 cores (4 threads) available, but a solution is indeed found for this particular case.

Even with 8 threads, I tried increasing the timeout condition by 10x (so the mapper will tries more combinations before stopping), but it did not find any solution still. What does not make sense to me is why for 24 threads, no solution is found why 16 threads can find one.

Thanks.
[testcase_threads.zip](https://github.com/NVlabs/timeloop/files/4927184/testcase_threads.zip)

**Comment by angshuman-parashar** [comment]
In general I wouldn't recommend using num-threads more than available hardware threads, that will only slow the mapper down. It's best to keep it un-set, in which case Timeloop will probe the number of available hardware threads and fork that many mapper threads. However, if you are trying to diagnose/debug the mapper's behavior then of course you can use the parameter.

To answer your specific question - when the mapper creates a certain number of threads, it partitions the mapspace among the threads. Due to the nature of the RNG it's hard to deterministically determine which specific mapping each thread will decide to visit. Therefore, you may see situations where a larger number of threads are behaving unexpectedly because they got unlucky and happened to visit a number of bad mappings. Could you please expand the timeout even further and see if it helps?

**Comment by egiacomin** [comment]
Got it. I will let the mapper use the available nb of threads automatically then.

As you said, looks like the 16 threads version got lucky and visited the good mapping very early. I increased the timeout by 100x and the 8/2 threads were able to find the same solution. Thanks for the insights.
