### ISSUE TITLE
Unnecessary writes on weights buffer

### ISSUE THREAD

**Issue by jgomez6** [NVlabs/timeloop#49]
Hello,
Thanks for all this work! 
I have a question about some unnecessary memory writes that the system seems to be doing. I defined a memory buffer only to store the weights. The size of this buffer is much larger than the size of all the weights. I also defined in the constraints to keep only the weights on this memory and I use a second buffer for the inputs and outputs. However, after Timeloops runs, this memory has been written much more times than the size of the total weights (that shouldn’t be necessary).  
In the example that I am attaching the buffer weights size is 512000B, the number of weights is 147456, and the number of times that the memory is filled is 4718592 (exactly 32 times the total size of the weights, probably I am missing something :) ).
Attach is an example that can be run using the command: 
timeloop-mapper arch/system.yaml arch/components/*.yaml mapper/mapper.yaml constraints/*.yaml Out_Conv_layer_VGG.yaml
I am also attaching my config file a  folder with a primitive that is needed. 
Thanks!
[Tests.zip](https://github.com/NVlabs/timeloop/files/4998536/Tests.zip)

**Comment by angshuman-parashar** [comment]
Look at the output mapping in timeloop-mapper.map.txt. You are holding a block of 96 weights at GlobalBuffer_2 (your Weights buffer). Now look at the loops *outside* of that level. As you walk through C=[0:4), K=[0:4), S=[0:3) you will be filling in new blocks of 96 weights into the weight buffer. However, when you get to the P=[0:2) loop, you will have to refetch all of those blocks once more from the beginning and apply them to produce the next set of output activations. And outside of that, at the MainMemory level, the P=[0:4) and Q=[0:4) causes another 16x re-fills of the weights.

**Comment by jgomez6** [comment]
Thanks for your answer, it makes sense given that mapping. However, is hard to see for me, how it can be that the optimal mapping includes paying several times the high price of bringing the same weights from the off-chip, given that there was available memory to keep those weights on the buffer. Is there a way to force a one time read of the weights from the off-chip memory to the GlobalBuffer_2 (just for checking )? Or to start as an initial condition with the weights on the GlobalBuffer_2? 
Thanks!

**Comment by angshuman-parashar** [comment]
Good question. I think it's partially a consequence of the "inverted" memory hierarchy you created in system.yaml, with a huge inner Weight buffer and a smaller outer Input buffer. We designed Timeloop's mapping formulation around a more traditional memory hierarchy with increasing capacities as you move closer to memory. Such a hierarchy is a good fit for mapping hierarchical tiles in structured linear algebra problems that we are targeting. Given this mapping approach, if Timeloop wanted to increase Weight buffer occupancy (e.g., by increasing K) then it would result in the Output tile also increasing in size at the Input/Output GlobalBuffer, which is probably already at or close to capacity.

The good news is that the fix is simple. If you swap the order of the 2 GlobalBuffers then it will transform the system into a standard memory hierarchy with increasing capacities. I suspect you'll see that the resultant mappings are more efficient and intuitive.

**Comment by jgomez6** [comment]
Thanks!, it worked, now the results make sense.
