### ISSUE TITLE
confusion with MeshX and clarity on split commands

### ISSUE THREAD

**Issue by RajuMachupalli** [NVlabs/timeloop#52]
# MeshX:
From slides of tutorial I understand meshX is used to divide the total number of components into XY-dimension. 
For example, from slide number 41 in tutorial (exercise 6), meshX is used to arrange RegFile[0..11] into 3X4 in XY-dimension. But in the provided eyeriss architecture .yaml file (attached image below), meshX is used inside the local InputRegFile/WeightRegFile/PsumRegFile 's attributes but not on PEs  attribute. Is that means meshX=14 is applied to individual InputRegFile/WeightRegFile/PsumRegFile if yes then how the 256 PEs are splitted in XY dimension?

![eyeriss_Arch_snip](https://user-images.githubusercontent.com/52839597/90330972-5abdb480-df6e-11ea-95e5-fa717cd5a256.PNG)

# Split: 
what does split do in constrain file, the explanation is missing in the video.
  - target: DummyBuffer
    type: spatial
    split: 4
    permutation: NPQR SCM
    factors: N=1 P=1 Q=1 R=1 S=0
  only allow fanout of M, Q out from glb
  - target: shared_glb
    type: spatial
    split: 7
    permutation: NCPRSQM
    factors: N=1 C=1 P=1 R=1 S=1
  one ofmap position but of different output channels

Thank you.

**Comment by angshuman-parashar** [comment]
Good questions. The meshX/Y attributes only apply to *local* nodes in the tree, and not to subtree levels such as "PE". Since the PE is constructed out of the 3 scratchpads and the mac, applying meshX/Y to all those local nodes has the effect of arranging the complete PE in those dimensions. You do have to keep them consistent.

Split describes how a *mapping* handles the meshX/Y arrangement of the hardware. Specifically, it determines which loops at a particular spatial level map onto the X vs. the Y dimension on the hardware. For example, in the above example, split=4 at the DummyBuffer will map the NPQR loops onto the X dimension and SCM onto Y. At the GLB level, split=7 will map all loops onto the X dimension of the hardware. If you are using the mapper and leave split un-specified, all split options will be exposed to the mapspace. For more detail please take a look at: https://github.com/NVlabs/timeloop/issues/26#issuecomment-620083102
