### ISSUE TITLE
Different NoC topologies simulation with timeloop?

### ISSUE THREAD

**Issue by manili** [NVlabs/timeloop#55]
Dear @angshuman-parashar,
Hello
As far as I know different NoC topologies could affect the overall performance, power and area of the accelerators. As an example the Microswitch (a novel custom topology) is causing much less latency and power compared to the Mesh topology [https://doi.org/10.1145/3130218.3130230].
So I'm really wondering to know if it is possible to simulate different NoC topologies (other than 2D-Mesh) with timeloop? If it is not, then is it worth it to contribute such feature to the project?
Thanks a lot for this nice project.

Kind Regards,
Manili

**Comment by angshuman-parashar** [comment]
Yes, it's certainly possible. We've designed timeloop's microarchitectural model to be modular. In fact, you can see multiple alternative network modules in the source code today. These modules register themselves with a unique name, and a user configuration YAML can instantiate any of the registered network modules between each pair of storage levels in an architecture setup. It is straightforward to add more alternative modules, as long as they export the same interface to Timeloop. This means that they need to take in a descriptor containing steady-state data-movement statistics and translate that to performance and energy projections. In other words, the module must be able to answer the question--how much time and energy will I consume in order to move the provided amount of data?

Now, a caveat is that the higher-level tile analysis does assume that nodes at a given architectural level (e.g. a set of PEs) have the ability to communicate with their *logical* neighbors (peers) in a mesh-like arrangement. However, the microarchitectural characteristics of the network used to achieve (a) this peer communication and (b) parent-to-child communication (e.g., a global buffer to a set of PEs) is completely up to the implementation of the specific network module that was instantiated by the user.

**Comment by manili** [comment]
Dear @angshuman-parashar,
Thanks a lot for the perfect and complete reply. I have two questions:
1. 
> **Now, a caveat is that the higher-level tile analysis does assume that nodes at a given architectural level (e.g. a set of PEs) have the ability to communicate with their _logical_ neighbors (peers) in a mesh-like arrangement.**

I'm afraid I did not understand the **Bold** part of your answer. You mean the Timeloop during higher-level analysis assumes we are using Mesh topology but during the estimation process it use the our custom topology via the provided module?

2. 
> In fact, you can see multiple alternative network modules in the source code today.
Would you mind show me some links of source code, please?

Again thanks a lot for your help.
Best regards,
Manili

**Comment by angshuman-parashar** [comment]
The mapper needs to have some consistent abstraction of the hardware so that it can enumerate the ways in which it can lay out the data and computation. It's helpful if this abstraction is consistent across various alternative microarchitectural implementations. We chose a mesh as this hardware abstraction.

From the mapper (and high level tile-analysis) point of view, what this means is that for a specific mapping, we measure the data movement between, (example 1) logical hardware coordinate (x,y) and logical hardware coordinate (x+1,y), and (example 2) the multicast data movement from a parent node to a subset of child nodes within an X*Y logical grid.

However, this high-level data movement analysis does not make any assumptions about the *cost* of these communications. It will simply record that N units of data must have been transferred between those logical hardware nodes in order to honor the mapping. This record of data movement is then passed through to the network module implementation to determine the cost of actually moving that data. That cost can be low (if the two logical units are close to each other in the physical topology), high (if they are farther apart and/or need multiple hops) or even infinite (if the two logical units actually can't reach each other in the physical topology, leading to an illegal mapping that will be dropped by the mapper).

Note that the cost-estimation provided by the network module is *in-loop* with the mapper's feedback loop. The mapper does not pre-judge whether a mapping is efficient or not without going through the full evaluation pipeline including all the network modules across the architecture. And so there shouldn't be any imprecision. However, if you feel that the logical mesh abstraction is problematic in terms of capturing your data movement patterns, then we should continue this discussion (perhaps over email).

For code examples, you can refer to model/network-legacy.* and model/network-reduction-tree.*.

By the way, to answer one of your original questions--yes, we would absolutely welcome contributions in the form of more interesting network topologies.

**Comment by manili** [comment]
Thanks a lot @angshuman-parashar. Really enjoyed the discussion. I think you answered all of my questions, However as you mentioned I still have a few questions about "logical mesh abstraction" in my mind and still it seems a little blurry to me. I'll try to reach you via your NVIDIA email (the email has been mentioned in your publications), ASAP.
Thanks a lot for your time and help.

Best regards,
Manili
