### ISSUE TITLE
Problem shape for group convolution

### ISSUE THREAD

**Issue by pratc3-coder** [NVlabs/timeloop#56]
Hi Sir,
Kindly suggest a way to modify the yaml file of problem for group convolution. 

Also, can you please let me know the difference in the latency obtained in flattened architecture and the cycle count come in mapper.stats.

Thanks in advance :)

**Comment by angshuman-parashar** [comment]
You can run grouped convolutions as scaled-down Timeloop runs and then scale the stats back up in post-processing. For example, if channel dims (C, K) = (64, 32) and group counts = 8, then run (C, K) = (8, 4) and post-process the stats (scale it 8 times).

The latency in flattened architecture is just the native latency of the hardware component, e.g.,  if it takes 5ns for a multiplier to perform a multiply, then it has a latency of 5ns. This is used by Accelergy plug-ins to calculate the actual energy consumption of the component (e.g., Aladdin plug-in uses that information), but is otherwise completely invisible to Timeloop model/mapper, which work at the cycle level. The cycle count in mapper.stats is the number of cycles it took to execute the mapping on the hardware.

**Comment by pratc3-coder** [comment]
Thank you sir, got it.
But what is the duration of one cycle?

**Comment by angshuman-parashar** [comment]
Cycle-level models work with a single cycle as the atomic unit of modeling fidelity. As far as the cycle-level model is concerned, a cycle could be 1ns or 1s, it does not matter.

**Comment by pratc3-coder** [comment]
Sir, I ran a model and got the cycle count 903168. Is there any way to find latency/time elapse?
