### ISSUE TITLE
How to get mapper output in yaml format as expected by timeloop-model executable?

### ISSUE THREAD

**Issue by vmiheer** [NVlabs/timeloop#70]
I tried dumping `.cfg` file but even after changing all files (arch/problem) in config file format, the cfg parsing fails.

**Comment by angshuman-parashar** [comment]
As you observed, emitting the optimal mapping in YAML format is currently not supported. We do intend to implement this as soon as possible. I apologize for the issues you are facing with CFG parsing. It should not fail, but we are probably going to spend our limited time in implementing YAML output instead of fixing CFG bugs. Please stay tuned.

**Comment by vmiheer** [comment]
Awesome thank you!

**Comment by FishSeeker** [comment]
It seems that when I use timeloop-mapper to parse .yaml (such as timeloop/configs/mapper/chen-asplos2014.yaml) file it can not generate .cfg file. But when I try to parse .cfg file by timeloop-mapper, it can generate .cfg file. Is there any params for timeloop-mapper to generate .cfg file?

**Comment by poant** [comment]
See commit 65322b43d3d2878bb18e46cae99b773c331cdd92
