### ISSUE TITLE
Question about simba config

### ISSUE THREAD

**Issue by vmiheer** [NVlabs/timeloop#72]
Hi I am looking at simba config and I have couple of questions
1. I think the constraints for [global buffer and dram](https://github.com/NVlabs/timeloop/blob/db033564c443c2dfa519427034e7cc2ceece3fda/configs/mapper/simba-chip.cfg#L209) about loop permutation/tilesizes are only for search space reduction purposes and not due to architectural constraints am I right? Are there any other constraints only for search space reduction?
2. In section 3.2, heading simba interconnect, it says. "Both NoC and NoP use a ***mesh*** topology with a hybrid wormhole/cut-through flowcontrol." I am assuming it as 2D mesh and not 1D mesh. Is that correct? And if that's correct, why does config for says [meshX = 16](https://github.com/NVlabs/timeloop/blob/db033564c443c2dfa519427034e7cc2ceece3fda/configs/mapper/simba-chip.cfg#L33) instead of 4 (rows) * 4 (pe/row) = 4 (rows) * 256 (pe/row), so meshX either 4 or 256?

**Comment by angshuman-parashar** [comment]
1. This is a great question, and I'm actually not 100% sure. I'll try to find out the answer. It's also possible that the constraints were written to mimic the behavior of Simba's custom mapper.
2.  It's a 2D mesh with X=16 and Y=1024/16=256.

**Comment by vmiheer** [comment]
Thanks @angshuman-parashar,
Sorry for slight confusion but my second question. It should've been: when simba paper calls something _**mesh**_, do they mean 1 dimentional mesh or 2 dimentional mesh? (I agree 1D mesh is still  a mesh, but simpler terminology in that case would be ring).

----

If I understood correctly, seems like timeloop simba config is modelling (perhaps for simplicity) 2D mesh of macs 16x64.
_This means the 256 and Y=1024/16=256._ seems typo with `s/256/64/g`.

----

3. And my last question I asked on one closed issue, I am posting it here in case you missed 😊 https://github.com/NVlabs/timeloop/issues/5#issuecomment-771179185

**Comment by angshuman-parashar** [comment]
Ah, I understand. Yes you're right there's a discrepancy between the Simba chiplet in Fig 3(a) of the paper showing 4x4 PEs and the Timeloop config in which all 16 PEs are laid out in a single row (which isn't really a mesh at all!). You should be able to precisely reproduce the paper's PE organization by setting meshX=4 for the input buffer, 32 for the weight/accumulation buffers and 256 for the weight regs and MAC units. However if you do that the Timeloop mapper will want to independently assign loops to either the X=4 or Y=4 dimensions instead of an architecturally-contiguous space of 16 PEs, which will disallow certain mappings (that perhaps the Simba custom mapper can support). We're working on evolving the Timeloop arch specification so that there is a separation between the logical architecture specs that the mapper sees (e.g., PEs=16) and the physical microarchitectural attributes (such as X/Y mesh), so discrepancies should go away in future.

**Comment by vmiheer** [comment]
Reopening for last question: https://github.com/NVlabs/timeloop/issues/5#issuecomment-773658766

**Comment by vmiheer** [comment]
Thank you so much!
