### ISSUE TITLE
Does Timeloop support more than one prob analysis?

### ISSUE THREAD

**Issue by vincentweisen1357** [NVlabs/timeloop#79]
Thanks for release Timeloop. I am wondering that does Timeloop support multiple prob mapping?

**Comment by angshuman-parashar** [comment]
Are you asking about simultaneous co-scheduling of multiple problems on the same architecture, or sequential scheduling of two problems (one after the other)? Both scenarios can be emulated using an outer script around Timeloop. The latter scenario can be emulated by calling Timeloop multiple times from the outer script. The former can be emulated by splitting the hardware into one partition for each problem, and running Timeloop independently for each hardware partition. The outer script can search through a space of possible partitionings in order to find an optimal solution.
