### ISSUE TITLE
timeloop reports Energy including static power and dynamic power

### ISSUE THREAD

**Issue by leehc257** [NVlabs/timeloop#91]
i have a question
timeloop makes Energy reports by user-defined architecture
this report shows Energy per  MACC every component and network
is this power including dynamic power and static power?
i think it just has static power because of all network power zero
is this true?

**Comment by angshuman-parashar** [comment]
It is all dynamic energy. If a component is showing zero energy that could be either because (a) there are 0 accesses to that component (e.g., a bypassed buffer) or (b) the technology model (you should be using Accelergy) is reporting 0 energy per access for that component. If it's (b), check the ERT.yaml to confirm. It could be a component that the specific Accelergy plugin you are using does not support yet. If so, you can file an issue with the Accelergy project. In specific cases, you can override the Accelergy numbers in Timeloop. For example, for a Legacy/XYNoC network you can set a `router_energy` and `wire_energy` attribute in the arch specs to override what the technology model is reporting.

**Comment by leehc257** [comment]
When I use the timeloop-mapper command, accelergy calculates ERT and timeloop uses ERT(i think so)
As you say it seems to be due to the router_energy and wire energy properties
Are there any examples for me to refer to?

router & wire energy are zeros
![image](https://user-images.githubusercontent.com/55521614/119919037-890ffc00-bfa4-11eb-945b-c96d11561f39.png)

result : (network energy is zero)
![image](https://user-images.githubusercontent.com/55521614/119919060-96c58180-bfa4-11eb-9ccb-155e97f211d6.png)
