### ISSUE TITLE
Questions about how the new release of Timeloop takes into account the actions of the components

### ISSUE THREAD

**Issue by GuillaumeDEVIC** [NVlabs/timeloop#98]
Hello,

I could see that you have released an update of Timeloop. The new version seems to better exploit the capabilities of Accelergy, taking into account the different actions of each component of an architecture. The estimations of energy consumption and energy efficiency should be more accurate.

I have two questions :

1. I have installed the new version of Timeloop, and I have run it with different architectures that I have.  But in the new `timeloop-mapper.stats.txt` file the `Actual Computes (total)`, `Gated Computes (total)` and `Skipped Computes` lines are 0.

    - Is it normal in the current state of the new version of Timeloop that these values are 0?
    - Or, should I apply in my architecture description new synthaxes?

2. With this new version of Timeloop, can I reasonably consider that the static power consumption of architectures is taken into account? ( Given that actions such as "idles" are taken into account, right? )

<br />

Thanks again for your interesting framework,

Best regards.

**Comment by angshuman-parashar** [comment]
1. The live master branch is now Timeloop V2 (a.k.a. Sparseloop), which is why you are seeing those sparsity-related additional statistics. V2 is fully backwards-compatible with V1, so if you specify a dense arch/problem with no sparsity optimizations, the sparsity-related statistics will be 0.
2. Not yet, but we are putting some of the machinery in place.
